const CDNURL = 'https://rbjesqwdqbrytthnjarh.supabase.co/storage/v1/object/public/media/'
const ANIMATION = 'animation/'
const SKETCH = 'sketch/'
const ZINE = 'zine/'
const CODE = 'code/'
const UX = 'ux/'

export const NAME_UNDERLINE = CDNURL + 'landing-underline-3.gif'
export const NAME_UNDERLINE_HIDDEN = CDNURL + 'landing-underline-hidden.png'

export const FLYING_HOME_STILL_URL = CDNURL + ANIMATION + 'flying-still.png'
export const GOODBYE_STILL_URL = CDNURL + ANIMATION + 'good-bye-still.png';
export const PROPOGATE_STILL_URL = CDNURL + ANIMATION + 'propogate-still.png'; 
export const SHADOWS_STILL_URL = CDNURL + ANIMATION + 'shadows-still.png'; 
export const FLYING_HOME_URL = CDNURL + ANIMATION + 'flying-home.mp4'
export const GOODBYE_URL = CDNURL + ANIMATION + 'good-bye.mp4'; 
export const PROPOGATE_URL = CDNURL + ANIMATION + 'propogate.mp4';
export const SHADOWS_URL = CDNURL + ANIMATION + 'shadows.mp4'; 

export const ZINE_TITLE = CDNURL + ZINE + 'Untitled_Artwork.jpg';
export const ZINE_1 = CDNURL + ZINE + 'Untitled_Artwork 1.jpg';
export const ZINE_2 = CDNURL + ZINE + 'Untitled_Artwork 2.jpg';
export const ZINE_3 = CDNURL + ZINE + 'Untitled_Artwork 3.jpg';
export const ZINE_4 = CDNURL + ZINE + 'Untitled_Artwork 4.jpg';
export const ZINE_5 = CDNURL + ZINE + 'Untitled_Artwork 5.jpg';
export const ZINE_6 = CDNURL + ZINE + 'Untitled_Artwork 6.jpg';
export const ZINE_7A = CDNURL + ZINE + 'Untitled_Artwork 7a.jpg';
export const ZINE_7B = CDNURL + ZINE + 'Untitled_Artwork 7b.jpg';
export const ZINE_8 = CDNURL + ZINE + 'Untitled_Artwork 8.jpg';
export const ZINE_9 = CDNURL + ZINE + 'Untitled_Artwork 9 Update.png';
export const ZINE_10 = CDNURL + ZINE + 'Untitled_Artwork 10.jpg';
export const ZINE_11 = CDNURL + ZINE + 'Untitled_Artwork 11.jpg';
export const ZINE_12 = CDNURL + ZINE + 'Untitled_Artwork 12.jpg';
export const ZINE_13 = CDNURL + ZINE + 'Untitled_Artwork 13.jpg';
export const ZINE_14 = CDNURL + ZINE + 'Untitled_Artwork 14.jpg';
export const ZINE_15 = CDNURL + ZINE + 'Untitled_Artwork 15.jpg';
export const ZINE_16 = CDNURL + ZINE + 'Untitled_Artwork 16.jpg';

export const IMG_1 = CDNURL + SKETCH + 'sketch_1.png';
export const IMG_2 = CDNURL + SKETCH + 'sketch_2.jpeg';
export const IMG_3 = CDNURL + SKETCH + 'sketch_3.jpg';
export const IMG_4 = CDNURL + SKETCH + 'sketch_4.jpeg';
export const IMG_5 = CDNURL + SKETCH + 'sketch_5.jpg';
export const IMG_6 = CDNURL + SKETCH + 'sketch_6.jpeg';
export const IMG_7 = CDNURL + SKETCH + 'sketch_7.png';
export const IMG_8 = CDNURL + SKETCH + 'sketch_8.jpg';
export const IMG_9 = CDNURL + SKETCH + 'sketch_9.jpg';
export const IMG_10 = CDNURL + SKETCH + 'sketch_10.JPG';
export const IMG_11 = CDNURL + SKETCH + 'sketch_11.jpeg';
export const IMG_12 = CDNURL + SKETCH + 'sketch_12.JPG';
export const IMG_13 = CDNURL + SKETCH + 'sketch_13.jpeg';
export const IMG_14 = CDNURL + SKETCH + 'sketch_14.jpg';
export const IMG_15 = CDNURL + SKETCH + 'sketch_15.JPG';
export const IMG_16 = CDNURL + SKETCH + 'sketch_16.png';
export const IMG_17 = CDNURL + SKETCH + 'sketch_17.jpeg';
export const IMG_18 = CDNURL + SKETCH + 'sketch_18.jpeg';
export const IMG_19 = CDNURL + SKETCH + 'sketch_19.jpg';
export const IMG_20 = CDNURL + SKETCH + 'sketch_20.JPG';
export const IMG_21 = CDNURL + SKETCH + 'sketch_21.jpeg';
export const IMG_22 = CDNURL + SKETCH + 'sketch_22.jpg';
export const IMG_23 = CDNURL + SKETCH + 'sketch_23.jpeg';
export const IMG_24 = CDNURL + SKETCH + 'sketch_24.JPG';
export const IMG_25 = CDNURL + SKETCH + 'sketch_25.jpeg';
export const IMG_26 = CDNURL + SKETCH + 'sketch_26.jpeg';
export const IMG_27 = CDNURL + SKETCH + 'sketch_27.jpeg';
export const IMG_28 = CDNURL + SKETCH + 'sketch_28.jpeg';
export const IMG_29 = CDNURL + SKETCH + 'sketch_29.jpeg';
export const IMG_30 = CDNURL + SKETCH + 'sketch_30.jpeg';
export const IMG_A = CDNURL + SKETCH + 'sketch_A.jpeg';

export const FLYING_HOME_GAME = CDNURL + CODE + '120-game-1.png'
export const MAZE_PROJECT = CDNURL + CODE + 'game3.png'
export const MAZE_PROJECT_2 = CDNURL + CODE + 'game2.png'
export const BAMBOO_PROJECT = CDNURL + CODE + 'multiple-branches.png'
export const SHADERS_PROJECT = CDNURL + CODE + 'monochrome.png'
export const PERSISTANCE_PROJECT = CDNURL + CODE + 'persistance-example.png'
export const PENROSE_GIF = CDNURL + CODE + 'reverse-penrose.gif'
export const MINECRAFT = CDNURL + CODE + 'minecraft-still.png'